title: "Hi, I'm Ella Beiser!"
logo: /assets/headshot 2.png
description: Bilingual journalist living in Chicago. I can be reached at my email, ellabeiser606@gmail.com.
show_downloads: false
theme: jekyll-theme-minimal
